### ISSUE TITLE
panic on GetStructure().UnmarshalInto()

### ISSUE THREAD

**Issue by brucekim** [tinyzimmer/go-gst#24]
It encounters panic when accessing unexported fields of struct at reflect.

In my case, I need to get GstRTPPacketLost event that as field name in lower case. So I need to define type struct in go area.
https://github.com/GStreamer/gst-plugins-good/blob/20bbeb5e37666c53c254c7b08470ad8a00d97630/gst/rtpmanager/gstrtpjitterbuffer.c#L2433-L2438

```go
type GstRTPPacketLostEvent struct {
	Seqnum		uint
	Timestamp	uint64
	Duration	uint64
	Retry		uint
}
```

Since reflect doesn't allow to set on unexported fields, this causes panic.

```bash
panic: reflect: reflect.Value.Set using value obtained using unexported field

goroutine 17 [running, locked to thread]:
reflect.flag.mustBeAssignableSlow(0xc314f2)
        /usr/local/go/src/reflect/value.go:259 +0xc5
reflect.flag.mustBeAssignable(...)
        /usr/local/go/src/reflect/value.go:249
reflect.Value.Set({0xcb4c80, 0xc000412840, 0x6}, {0xcb4c80, 0x157f428, 0xcb4c80})
        /usr/local/go/src/reflect/value.go:1899 +0x6a
```

I figured out an workaround by lowering `fieldName` then set on `UnmarshalInto`.
However this is limited to cover only lower case of field name.

I am figuring out better way for this.

```go
func (s *Structure) UnmarshalInto(data interface{}) error {
	rv := reflect.ValueOf(data)
	if rv.Kind() != reflect.Ptr || rv.IsNil() {
		return errors.New("Data is invalid (nil or non-pointer)")
	}

	val := reflect.ValueOf(data).Elem()
	nVal := rv.Elem()
	for i := 0; i < val.NumField(); i++ {
		nvField := nVal.Field(i)
		fieldName := val.Type().Field(i).Name
		val, err := s.GetValue(strings.ToLower(fieldName))
		if err == nil {
			nvField.Set(reflect.ValueOf(val))
		}
	}

	return nil
}
```

**Comment by RSWilli** [comment]
@brucekim I have some ideas involving reflection tags to fix this issue. If you still need this, move the issue please and continue the discussion at https://github.com/go-gst/go-gst (where future development of the bindings will take place)
